### ISSUE TITLE
Wrong ids in Minecraft ID List

### ISSUE THREAD

**Issue by moldcraft** [grahamedgecombe/minecraft-installer#10]
*The contact form on your site seems broken, so I contact you here.*

http://minecraft-ids.grahamedgecombe.com/

![~](https://static.md/02e8c0a3be8076423ab25b52089ed3a1.png)
![~](https://static.md/4733968279ed955d8d3c716de86d8f04.png)

**Comment by moldcraft** [comment]
Also Cooked fish text id is wrong

![~](https://static.md/f93f79e38e2ce955d1a33d58ce95dac4.png)
![~](https://static.md/5cfe79f4b7c620c203b95df6b068e5a9.png)

**Comment by grahamedgecombe** [comment]
`cooked_fish` works for me in 1.8.4. The rest are fixed now.

**Comment by moldcraft** [comment]
> cooked_fish works for me in 1.8.4

ok, I tested on 1.7

----

Thanks
